name: "tasks-app"

services:
  backend:
    image: backend:0.0.2
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      - db
    environment:
      - SERVER_PORT= 8181
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/tasks-app
    container_name: tasks-app-backend

  db:
    image: postgres:12.12-alpine
    ports:
      - "9876:5432"
    volumes:
      - /home/user/tasks-app/pgdata_ci:/var/lib/postgresql/data
      - ./sql/create_database_tasks-app_logs.sql:/docker-entrypoint-initdb.d/create_database_tasks-app_logs.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    container_name: tasks-app-db
    restart: always

  pgadmin:
    container_name: tasks-app-pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"